inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 2.5.8

Layout/SpaceBeforeBrackets:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false
